version: '3.8'
services:
  jenkins:
    container_name: jenkins
    build:
      context: ./master
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc.yaml
    hostname: jenkins

  agent1:
    container_name: agent1
    init: true
    build:
      context: ./nodes
      dockerfile: Dockerfile
    command: ["sleep", "infinity"]

  agent2:
    container_name: agent2
    init: true
    build:
      context: ./nodes
      dockerfile: Dockerfile
    command: ["sleep", "infinity"]

  agent3:
    container_name: agent3
    init: true
    build:
      context: ./nodes
      dockerfile: Dockerfile
    command: ["sleep", "infinity"]

volumes:
  jenkins_home: